apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/wordpress
    server: 172.31.85.249
  persistentVolumeReclaimPolicy: Retain
